soloistrc.E0000002021: Replace osxfuse by macfuse
Error was:

        ================================================================================
        Error executing action `install` on resource 'homebrew_cask[osxfuse]'
        ================================================================================

        Mixlib::ShellOut::ShellCommandFailed
        ------------------------------------
        Expected process to exit with [0], but received '1'
        ---- Begin output of /opt/homebrew/bin/brew install --cask osxfuse  ----
        STDOUT: ==> Caveats
        `osxfuse` has been succeeded by `macfuse` as of version 4.0.0.

        To update to a newer version, do:
          brew uninstall osxfuse
          brew install macfuse

        osxfuse requires a kernel extension to work.
        If the installation fails, retry after you enable it in:
          System Preferences → Security & Privacy → General

        For more information, refer to vendor documentation or this Apple Technical Note:
          https://developer.apple.com/library/content/technotes/tn2459/_index.html

        You must reboot for the installation of osxfuse to take effect.

        ==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.11.2/osxfuse-3.11.2.dmg
        ==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/1867347/ab8d9600-06f1-11eb-9e31-17e04b5951ce?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220407T183551Z&X-Amz-Expires=300&X-Amz-Signature=9daebaeca9de13335577d12d069c2669ad0cfec0cf7bf49abe8902c56eee1d13&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1867347&response-content-disposition=attachment%3B%20filename%3Dosxfuse-3.11.2.dmg&response-content-type=application%2Foctet-stream
        ==> Installing Cask osxfuse
        ==> Running installer for osxfuse; your password may be necessary.
        Package installers may write to any location; options such as `--appdir` are ignored.
        ==> Purging files for version 3.11.2 of Cask osxfuse
        STDERR: installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.
        Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=jcuzella USER=jcuzella USERNAME=jcuzella /usr/sbin/installer -pkg /opt/homebrew/Caskroom/osxfuse/3.11.2/Extras/FUSE\ for\ macOS\ 3.11.2.pkg -target /` exited with 1. Here's the output:
        installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.
        ---- End output of /opt/homebrew/bin/brew install --cask osxfuse  ----
        Ran /opt/homebrew/bin/brew install --cask osxfuse  returned 1

        Cookbook Trace:
        ---------------
        /var/chef/cache/cookbooks/homebrew/resources/cask.rb:35:in `block (2 levels) in class_from_file'
        /var/chef/cache/cookbooks/homebrew/resources/cask.rb:34:in `block in class_from_file'

        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/homebrew/recipes/install_casks.rb

         21:   homebrew_cask cask
         22: end

        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/homebrew/recipes/install_casks.rb:21:in `block in from_file'

        homebrew_cask("osxfuse") do
          action [:install]
          default_guard_interpreter :default
          declared_type :homebrew_cask
          cookbook_name "homebrew"
          recipe_name "install_casks"
          homebrew_path "/opt/homebrew/bin/brew"
          owner "jcuzella"
        end

        System Info:
        ------------
        chef_version=13.10.0
        platform=macos
        platform_version=12.3.1
        ruby=ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21]
        program_name=chef-solo worker: ppid=48510;start=12:34:51;
        executable=/Users/jcuzella/src/pub/soloist/sprout-wrap/vendor/bundle/ruby/2.7.0/bin/chef-solo

    [2022-04-07T12:35:57-06:00] INFO: Running queued delayed notifications before re-raising exception
    [2022-04-07T12:35:57-06:00] INFO: Running queued delayed notifications before re-raising exception

    Running handlers:
    [2022-04-07T12:35:57-06:00] ERROR: Running exception handlers
    [2022-04-07T12:35:57-06:00] ERROR: Running exception handlers
    Running handlers complete
    [2022-04-07T12:35:57-06:00] ERROR: Exception handlers complete
    [2022-04-07T12:35:57-06:00] ERROR: Exception handlers complete
    Chef Client failed. 1 resources updated in 01 minutes 05 seconds
    [2022-04-07T12:35:57-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    [2022-04-07T12:35:57-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    [2022-04-07T12:35:57-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    [2022-04-07T12:35:57-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    [2022-04-07T12:35:57-06:00] ERROR: homebrew_cask[osxfuse] (homebrew::install_casks line 21) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/homebrew/bin/brew install --cask osxfuse  ----
    STDOUT: ==> Caveats
    `osxfuse` has been succeeded by `macfuse` as of version 4.0.0.

    To update to a newer version, do:
      brew uninstall osxfuse
      brew install macfuse

    osxfuse requires a kernel extension to work.
    If the installation fails, retry after you enable it in:
      System Preferences → Security & Privacy → General

    For more information, refer to vendor documentation or this Apple Technical Note:
      https://developer.apple.com/library/content/technotes/tn2459/_index.html

    You must reboot for the installation of osxfuse to take effect.

    ==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.11.2/osxfuse-3.11.2.dmg
    ==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/1867347/ab8d9600-06f1-11eb-9e31-17e04b5951ce?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220407T183551Z&X-Amz-Expires=300&X-Amz-Signature=9daebaeca9de13335577d12d069c2669ad0cfec0cf7bf49abe8902c56eee1d13&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1867347&response-content-disposition=attachment%3B%20filename%3Dosxfuse-3.11.2.dmg&response-content-type=application%2Foctet-stream
    ==> Installing Cask osxfuse
    ==> Running installer for osxfuse; your password may be necessary.
    Package installers may write to any location; options such as `--appdir` are ignored.
    ==> Purging files for version 3.11.2 of Cask osxfuse
    STDERR: installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.
    Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=jcuzella USER=jcuzella USERNAME=jcuzella /usr/sbin/installer -pkg /opt/homebrew/Caskroom/osxfuse/3.11.2/Extras/FUSE\ for\ macOS\ 3.11.2.pkg -target /` exited with 1. Here's the output:
    installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.
    ---- End output of /opt/homebrew/bin/brew install --cask osxfuse  ----
    Ran /opt/homebrew/bin/brew install --cask osxfuse  returned 1
    [2022-04-07T12:35:57-06:00] ERROR: homebrew_cask[osxfuse] (homebrew::install_casks line 21) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/homebrew/bin/brew install --cask osxfuse  ----
    STDOUT: ==> Caveats
    `osxfuse` has been succeeded by `macfuse` as of version 4.0.0.

    To update to a newer version, do:
      brew uninstall osxfuse
      brew install macfuse

    osxfuse requires a kernel extension to work.
    If the installation fails, retry after you enable it in:
      System Preferences → Security & Privacy → General

    For more information, refer to vendor documentation or this Apple Technical Note:
      https://developer.apple.com/library/content/technotes/tn2459/_index.html

    You must reboot for the installation of osxfuse to take effect.

    ==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.11.2/osxfuse-3.11.2.dmg
    ==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/1867347/ab8d9600-06f1-11eb-9e31-17e04b5951ce?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220407%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220407T183551Z&X-Amz-Expires=300&X-Amz-Signature=9daebaeca9de13335577d12d069c2669ad0cfec0cf7bf49abe8902c56eee1d13&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1867347&response-content-disposition=attachment%3B%20filename%3Dosxfuse-3.11.2.dmg&response-content-type=application%2Foctet-stream
    ==> Installing Cask osxfuse
    ==> Running installer for osxfuse; your password may be necessary.
    Package installers may write to any location; options such as `--appdir` are ignored.
    ==> Purging files for version 3.11.2 of Cask osxfuse
    STDERR: installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.
    Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=jcuzella USER=jcuzella USERNAME=jcuzella /usr/sbin/installer -pkg /opt/homebrew/Caskroom/osxfuse/3.11.2/Extras/FUSE\ for\ macOS\ 3.11.2.pkg -target /` exited with 1. Here's the output:
    installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.
    ---- End output of /opt/homebrew/bin/brew install --cask osxfuse  ----
    Ran /opt/homebrew/bin/brew install --cask osxfuse  returned 1