soloistrc.E0000002021: Remove virtualbox b/c it requires x86_64 arch
Error was:

    ================================================================================
    Error executing action `install` on resource 'homebrew_cask[virtualbox]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/homebrew/bin/brew install --cask virtualbox  ----
    STDOUT: ==> Caveats
    virtualbox requires a kernel extension to work.
    If the installation fails, retry after you enable it in:
      System Preferences → Security & Privacy → General

    For more information, refer to vendor documentation or this Apple Technical Note:
      https://developer.apple.com/library/content/technotes/tn2459/_index.html

    ==> Downloading https://download.virtualbox.org/virtualbox/6.1.32/VirtualBox-6.1.32-149290-OSX.dmg
    STDERR: Running `brew update --preinstall`...
    ==> Auto-updated Homebrew!
    Updated Homebrew from 33709297c to 9c58f9a77.
    Updated 6 taps (homebrew/cask-versions, homebrew/core, homebrew/cask, homebrew/bundle, homebrew/services and homebrew/cask-drivers).
    ==> New Formulae
    autocannon
    criterion
    ddcutil
    difftastic
    highs
    ifacemaker
    imposm3
    kmod
    libcython
    mariadb@10.6
    mongodb-atlas-cli
    nvchecker
    ugit
    ==> Updated Formulae
    Updated 354 formulae.
    ==> Deleted Formulae
    griffon
    ==> New Casks
    accord
    anypointstudio
    audiorelay
    bettermouse
    droidcam-obs
    free-gpgmail
    kdenlive
    logi-options-plus
    osp-tracker
    polymc
    postman-agent
    readyapi
    warp
    ==> Updated Casks
    Updated 343 casks.

    ==> Homebrew was updated to version 3.4.5
    The changelog can be found at:
      https://github.com/Homebrew/brew/releases/tag/3.4.5
    Error: Cask virtualbox depends on hardware architecture being one of [{:type=>:intel, :bits=>64}], but you are running {:type=>:arm, :bits=>64}.
    ---- End output of /opt/homebrew/bin/brew install --cask virtualbox  ----
    Ran /opt/homebrew/bin/brew install --cask virtualbox  returned 1